### ISSUE TITLE
Error importing PPO

### ISSUE THREAD

**Issue by joaomatoscf** [iffiX/machin#15]
Hi,

I was using machin until today, but I think it there was a super recent update and now my code stopped working (only for PPO, DQN still works).

With version 0.4.0 I get the error (when importing "from machin.frame.algorithms import PPO"):
ModuleNotFoundError: No module named 'machin.frame.helpers'

And if I install version 0.3.4 I get the error (when updating PPO):
AttributeError: 'PPO' object has no attribute 'grad_max'

Joao

**Comment by iffiX** [comment]
For the grad_max problem, this is because I just changed it to "gradient_max" so users can access the same name as they have passed in __init__.

For the helpers import problem, I am not sure what could cause that, could you please show the import section of your code?

**Comment by joaomatoscf** [comment]
Here is the error I get when running "import machin"

![image](https://user-images.githubusercontent.com/48652511/114938521-19e8a900-9e37-11eb-88f8-8d24d83543af.png)

This was working until this morning.

**Comment by iffiX** [comment]
Hi, the fix is very simple, I will upload it later. Currently, I am fixing my testing infrastructure so such import errors will be detected in the future.

**As a temporary fix**, you can clone this repository and **install it in editable mode with `pip install -e .`**, this installation method will link to the machin code directory, so "frame.helpers" can be found (which is not present in \_\_all\_\_ when installing from pypi or setup.py)

**Comment by iffiX** [comment]
Fixed with 8841c618e2a5eb184085da11d3d35c56cf820a88
